import {
  PenTool,
  Video,
  Palette,
  TrendingUp,
  Smartphone,
  Bot,
  Code,
} from "lucide-react";

export const jobListings = [
  {
    id: "content-writer",
    title: "Content Writer / Copywriter",
    department: "Marketing",
    experience: "Entry to Mid Level",
    workType: "On-site",
    employment: "Part-time",
    pay: "10,000 - 20,000/month",
    location: "Lucknow, India",
    icon: PenTool,
    description:
      "We're hiring a Content Writer who can write clear, compelling copy for blogs, social media, and more. If you love crafting words, enjoy storytelling, and can adapt tone based on context — we want to hear from you. You'll work alongside our team to build our content presence across platforms.",
    responsibilities: [
      "Create engaging content for blogs, websites, and social media",
      "Develop marketing copy for campaigns and promotions",
      "Collaborate with designers to create cohesive content",
      "Research industry-related topics to ensure factual accuracy",
      "Optimize content for SEO and audience engagement",
    ],
    requirements: [
      "Excellent command of written English",
      "Minimal grammatical errors and strong proofreading skills",
      "Ability to write blog posts, LinkedIn articles, social captions, and more",
      "Strong research skills to write informative and engaging content",
      "Collaborate with designers and marketers for campaign writing",
      "Creative, adaptable, and deadline-oriented",
    ],
    perks: [
      "Flexible working hours",
      "Creative freedom",
      "Portfolio-building projects",
    ],
  },
  {
    id: "video-editor",
    title: "Video Editor",
    department: "Creative",
    experience: "1-2 years preferred",
    workType: "Hybrid",
    employment: "Part-time",
    pay: "15,000 - 25,000/month",
    location: "Lucknow, India",
    icon: Video,
    description:
      "We're on the lookout for a talented Video Editor who can craft compelling videos that engage and inform. You'll collaborate with our creative and marketing teams to produce high-quality edits for reels, campaigns, and more. If you're passionate about storytelling through visuals and have a good grasp of editing tools — this is for you.",
    responsibilities: [
      "Edit raw footage into polished videos for various platforms",
      "Create motion graphics and animations",
      "Color correction and audio mixing",
      "Collaborate with content team to develop video concepts",
      "Manage media assets and maintain organized libraries",
    ],
    requirements: [
      "Proficiency in Adobe Premiere Pro or DaVinci Resolve",
      "Basic understanding of color grading, transitions, and audio syncing",
      "Ability to manage multiple projects with tight deadlines",
      "Familiarity with modern video content formats (reels, shorts, etc.)",
      "Collaborate effectively with creative and content teams",
      "Open to feedback and eager to improve with every cut",
    ],
    perks: [
      "Access to premium editing tools",
      "Creative collaboration with talented team",
      "Showcase work on high-profile projects",
    ],
  },
  {
    id: "graphic-designer",
    title: "Graphic Designer",
    department: "Creative",
    experience: "1-3 years",
    workType: "Hybrid",
    employment: "Part-time",
    pay: "12,000 - 22,000/month",
    location: "Lucknow, India",
    icon: Palette,
    description:
      "We're seeking a creative Graphic Designer who can bring ideas to life visually. You'll work closely with our content and marketing teams to design impactful graphics for digital and print, aligning with our brand tone and style. If you're detail-oriented, collaborative, and design-savvy — we'd love to have you on board.",
    responsibilities: [
      "Create visual content for digital and print media",
      "Develop branding materials and marketing collateral",
      "Design social media graphics and campaigns",
      "Collaborate with marketing team on visual strategy",
      "Maintain brand consistency across all designs",
    ],
    requirements: [
      "Proficiency in Photoshop and CorelDRAW",
      "Familiarity with Canva and Figma (Figma is a plus)",
      "Strong eye for aesthetics and design consistency",
      "Ability to interpret briefs and translate them into designs",
      "Comfortable collaborating with various teams and working under tight deadlines",
      "Willing to learn and adapt to different styles and formats",
    ],
    perks: [
      "Creative autonomy",
      "Diverse project portfolio",
      "Skill development opportunities",
    ],
  },
  {
    id: "business-development",
    title: "Business Development Specialist",
    department: "Growth",
    experience: "0-1 years",
    workType: "Hybrid",
    employment: "Part-time",
    pay: "15,000 + performance bonuses",
    location: "Lucknow, India",
    icon: TrendingUp,
    description:
      "We're looking for a BD Specialist who thrives on identifying new opportunities, delivering compelling sales pitches, and driving conversions. You'll be at the front line building meaningful connections, representing our vision, and helping us scale with purpose. If you're persuasive, confident, and results-driven — this role is for you.",
    responsibilities: [
      "Identify and pursue new business opportunities",
      "Develop and maintain client relationships",
      "Prepare and deliver sales presentations",
      "Negotiate contracts and close deals",
      "Collaborate with marketing on lead generation",
    ],
    requirements: [
      "Excellent sales pitching and communication skills",
      "Ability to understand client needs and position offerings effectively",
      "Strategic thinker with a doer's mindset",
      "Comfortable handling outreach, calls, and closing deals",
      "Experience or interest in the startup/growth ecosystem",
      "Willing to learn fast and adapt on the go",
    ],
    perks: [
      "Uncapped earning potential",
      "Professional development",
      "Networking opportunities",
    ],
  },
  {
    id: "ui-ux-designer",
    title: "UI/UX Designer",
    department: "Design",
    experience: "0-2 years",
    workType: "Hybrid",
    employment: "Part-time",
    pay: "18,000 - 30,000/month",
    location: "Lucknow, India",
    icon: Smartphone,
    description:
      "We need a creative thinker who can turn ideas into beautiful, usable interfaces. You'll work closely with the product and dev teams to bring digital experiences to life with clear UX and clean UI.",
    responsibilities: [
      "Design user interfaces for web and mobile",
      "Create wireframes and prototypes",
      "Conduct user research and testing",
      "Collaborate with developers on implementation",
      "Maintain design systems and style guides",
    ],
    requirements: [
      "Proficient with Figma and interface design principles",
      "Understands UX flows, wireframes, and component systems",
      "Attention to detail and eye for typography, spacing, and alignment",
      "Collaborative mindset and eagerness to grow",
    ],
    perks: [
      "Work on cutting-edge products",
      "User-centered design focus",
      "Career growth opportunities",
    ],
  },
  {
    id: "ai-developer",
    title: "AI Developer",
    department: "Tech Innovation",
    experience: "0-2 years",
    workType: "Remote",
    employment: "Part-time",
    pay: "20,000 - 35,000/month",
    location: "Remote (India)",
    icon: Bot,
    description:
      "We're seeking someone who can creatively build automations using LLMs and AI APIs. You should be passionate about leveraging AI to solve real problems and ready to prototype fast and ship often.",
    responsibilities: [
      "Develop AI-powered applications and features",
      "Integrate LLM APIs into existing systems",
      "Optimize AI model performance",
      "Research and implement new AI technologies",
      "Collaborate with product team on AI solutions",
    ],
    requirements: [
      "Hands-on with LLMs and tools like OpenAI, HuggingFace, LangChain etc.",
      "Can integrate APIs and build workflows around them",
      "Knows how to automate boring stuff with code",
      "Adaptable and excited to work in a fast-paced, experimental environment",
    ],
    perks: [
      "Work with cutting-edge AI tech",
      "Flexible remote work",
      "Innovation-driven projects",
    ],
  },
  {
    id: "software-engineer",
    title: "Software Development Engineer",
    department: "Engineering",
    experience: "0-2 years",
    workType: "Hybrid",
    employment: "Part-time",
    pay: "20,000 - 40,000/month",
    location: "Lucknow, India",
    icon: Code,
    description:
      "We're looking for a developer who can work on both frontend and backend — whether it's a web app using React/Next.js or a mobile app using React Native. You'll contribute to building scalable cross-platform applications and backend systems using Express.js. We value curiosity, self-motivation, and a hunger to grow.",
    responsibilities: [
      "Develop and maintain web/mobile applications",
      "Write clean, efficient, and documented code",
      "Collaborate with designers on UI implementation",
      "Debug and optimize application performance",
      "Participate in code reviews",
    ],
    requirements: [
      "Hands-on experience with any frontend framework — React, Next.js (web) or React Native (mobile)",
      "Working knowledge of Express.js and REST APIs",
      "Familiarity with the MERN stack is a big plus",
      "Ability to debug and optimize frontend and backend performance",
      "Willingness to take ownership and learn quickly",
    ],
    perks: [
      "Modern tech stack",
      "Mentorship program",
      "Product ownership opportunities",
    ],
  },
] as const;

export type JobListing = (typeof jobListings)[number];
